codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default